project:
  type: book
  output-dir: docs

book:
  title: "Inferencia Estadística"
  author: "Biviana M. Suárez Sierra"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd

format:
  html:
    theme: cosmo
    toc: true
    mermaid: {}
    toc-depth: 3
    toc-location: right
    callout-appearance: default
    number-sections: true
    html-math-method: mathjax
    reference-location: margin
    fig-cap-location: top
    citations-hover: true
    code-link: true

theorem-environments:
  - name: definition
    title: "Resultado"
  - name: theorem
    title: "Teorema"
  - name: lemma
    title: "Lema"
  - name: proposition
    title: "Proposición"
  - name: corollary
    title: "Corolario"
  - name: example
    title: "Ejemplo"
  - name: remark
    title: "Observación"
  - name: proof
    title: "Demostración"
