project:
  type: book
  output-dir: docs

book:
  title: "Inferencia Estadística"
  author: "Biviana M. Suárez Sierra"
  chapters:
    - index.qmd
    - "Datos y modelos.qmd"
    - "Variable aleatoria.qmd"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: right
    navigation:
      search: true
    number-sections: true
    html-math-method: mathjax

